name: Blocking Issues

on:
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  pull_request_target:
    types: [opened, edited, closed, reopened]

jobs:
  blocking_issues:
    permissions:
      checks: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Check for blocking issues
    steps:
      - uses: Levi-Lesches/blocking-issues@v2
        continue-on-error: true
        with:
          use-label: "blocked"
