# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# For more information on using and configuring these actions, see:
# https://instantiator.dev/presence/gha/format-and-post-with-gha.html

name: on-push-test-actions
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - format-thread/**
      - post-thread/**
    
jobs:
  format-simple-thread:
    runs-on: ubuntu-latest
    steps:
      # 1. create and post a thread from input provided in the workflow

      - name: Format a basic thread
        id: format-basic-thread
        uses: instantiator/presence/format-thread@main
        with:
          networks: 'Console,AT'
          imput-format: 'MD'
          input-content: |
            This is a simple thread posted from GitHub Actions, with a simple link: [Presence documentation](https://instantiator.dev/presence)

            It contains a minimum of two posts. #Test #GHA #Posting #SocialNetworks #Presence
      - name: Summarise basic thread formatting activity
        run: echo "${{ steps.format-basic-thread.outputs.format-response }}"
      - name: Post the basic thread to console
        id: post-basic-thread
        uses: instantiator/presence/post-thread@main
        with:
          thread: ${{ steps.format-basic-thread.outputs.format-response }}
          config: ${{ toJson(secrets) }}
      - name: Summarise the basic thread posting activity
        run: echo "${{ steps.post-basic-thread.outputs.post-thread-summary }}"

      # 2. create and post a thread from input provided from a file in the repository

      - uses: actions/checkout@v4
      - name: Format sample thread from file
        id: format-sample-thread
        uses: instantiator/presence/format-thread@main
        with:
          networks: 'Console,AT'
          input-file: 'SampleData/SimpleThread.md'
      - name: Summarise sample thread formatting activity
        run: echo "${{ steps.format-sample-thread.outputs.format-response }}"
      - name: Post the sample thread to console
        id: post-sample-thread
        uses: instantiator/presence/post-thread@main
        with:
          thread: ${{ steps.format-sample-thread.outputs.format-response }}
          config: ${{ toJson(secrets) }}
      - name: Summarise the sample thread posting activity
        run: echo "${{ steps.post-sample-thread.outputs.post-thread-summary }}"
