# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: test-actions
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - format-thread/**
      - post-thread/**
  pull_request:
    branches:
      - "*"
    paths:
      - format-thread/**
      - post-thread/**
    
jobs:
  format-simple-thread:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format sample thread
        id: format-thread
        uses: instantiator/presence/format-thread@main
        with:
          networks: 'Console'
          input-file: 'SampleData/SimpleThread.md'
      - name: Post sample thread to console
        id: post-thread
        uses: instantiator/presence/post-thread@main
        with:
          thread: ${{ steps.format-thread.outputs.format-response }}
          config: "{ \"PRESENCE_ACCOUNTS\": \"TEST0\", \"TEST0_CONSOLE_PRINTPREFIX\": \"[TEST0-GHA]\" }"
          # simplest case if you've no other important secrets: provide all your secrets as a JSON object
          # config: ${{ toJson(secrets) }}
      - name: Summarise activity
        id: summarise
        run: echo "${{ steps.post-thread.outputs.post-thread-summary }}"
