# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: test-actions
on:
  workflow_dispatch:

jobs:
  format-simple-thread:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format sample thread
        id: format-thread
        uses: instantiator/presence/format-thread@main
        with:
          networks: 'Console'
          input-file: 'SampleData/SimpleThread.md'
      - name: Post sample thread to console
        id: post-thread
        uses: instantiator/presence/post-thread@main
        with:
          thread: ${{ steps.format-thread.outputs.format-response }}
          config: ${{ toJson(secrets) }}
      - name: Summarise activity
        id: summarise
        run: echo "${{ steps.post-thread.outputs.post-thread-summary }}"
